#!/bin/bash

########## VARS ########
JDK_HOME=/usr/lib/jvm/jdk1.7.0
DIRECTORY=native/linux/x86_64

#create directory to hold compiled code
if [ ! -d "$DIRECTORY" ]; then
    mkdir native native/linux native/linux/x86_64
fi

#compile
g++ src/$DIRECTORY/MyNative.c -I $JDK_HOME/include -I $JDK_HOME/include/linux -l ncurses -shared -o $DIRECTORY/libMyNative.so -fPIC
